name: Go ERP Event Bus CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26.5'

      - name: Install dependencies
        run: go mod download

      - name: Build Codebase
        run: go build -v ./...

      - name: Run Tests
        run: go test -v ./...
